services:
  - type: web
    name: anonymus-chat-backend
    env: node
    plan: free
    buildCommand: npm run build:client && npm install
    startCommand: npx tsx server/src/index.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_KEY
        generateValue: true
